### ISSUE TITLE
PRD: Loans on Scan `Epic` 

### ISSUE THREAD

**Issue by ngyingzhong** [DeFiCh/scan#493]
## Background

[Decentralised loan](https://github.com/DeFiCh/pinkpaper/tree/main/loan) is slated to be released on the DeFiChain light wallet during 3rd week of November (TBC). To provide transparency to the community, it is important to reflect all loan-related transactions on DeFiChain through DeFi Scan. This includes vaults information, auctioned vaults, and loans undertaken.

## Objectives

- To continue serving as a transparent and open-sourced community
- To engage the community by providing them with a view of the activities relating to decentralised loans that are taking place on DeFiChain

## Key Success Metrics

1. Page views
2. Unique vault searches per month
3. App downloads

## User Stories

| User Story      | Link to Issue |
| ----------- | ----------- |
| Users want to find a specific vault      | #450       |
| Users want to get an overview of the vaults that exist on DeFiChain| #450  |
| Users want to see the list of vaults that are being auctioned  | #462      |
| Users wants to get a snapshot of key loan activities taking place on the home page | #478    |

## User Flow
![image](https://user-images.githubusercontent.com/66629826/139398840-b4cf8ee3-d7db-4baf-8ed7-921897479e60.png)

### Site hierarchy
`/*`

- `/vaults`
    - `/vaults/:vaultid`
- `/auctions` (→ when clicked, leads to specific `/vaults/:vaultid` page)

### Relationship between `/:vaultid` and `/auctions` page

- `/:vaultid` page will showcase all vault-related information as stated in #450, including vault state (i.e. safe / liquidated)
    - Auction information (explained in #462) will be a modular component on a specific vault page, where only liquidated vaults page will display auction info such as latest bids, type of auction etc. 
    - **Design consideration**: `/:vaultid` pages that are liquidated (i.e. in auction) should be highlighted e.g. different page background colour.
    - If users are to click on any vaults in auction on the `/auctions` page, it will lead to the `/:vaultid` page, with the auction information displayed on top of standard vault information.

## Task Summary
- [ ] `/vaults` page
- [ ] `/vaults/:vaultid` page
- [ ] `/auctions` page
- [ ] Home page updates
    - [ ] Search bar label to include "Vault ID"
 
## Sign-off by
@fuxingloh 
@joeldavidw
