### ISSUE TITLE
PRD: Viewing OCG Proposals on Scan `Story`

### ISSUE THREAD

**Issue by ngyingzhong** [DeFiCh/scan#677]
## Background

Proposal discussions lie at the heart of CFPs as it helps proposers gather feedback for their ideas, and more importantly showcases the community's motivations and goals for DeFiChain. CFPs are the core of the blockchain as it directs its trajectory through decentralized governance.

## Objectives

1. Provide greater transparency to all proposals and their voting process
2. To facilitate proposal discussions
3. To provide greater accessibility to proposal discussions

## Assumptions

1. Discussions can take place anywhere — Reddit, GitHub, Twitter, Discord etc. 
2. The technical requirements to allow discussion on Scan is too large at the moment, and we will only provide view-only access to discussions (link users out to respective platforms) 

## Key Success Metrics

1. Number of unique views on proposals
2. Number of link clicks to discussion links

## User Story: Proposal disussion and viewing voting process

This story is catered for the following users:

1. Proposal owners who want to view the voting process of their proposals
2. Eligible voters who are seeking an overview of the proposals in the voting cycle

![image](https://user-images.githubusercontent.com/66629826/144422052-f89defdb-07f0-4245-9c56-3caa7410988c.png)

### **Proposed features/ interactions:**

**Proposals overview page ("Governance")**

This page should:

1. Serve as a repository of all proposals on DeFiChain, segmented into current and past proposals
2. Highlight the stage of the voting cycle — i.e. Proposal Submission, Request for Comment, Voting.
3. Clearly distinguish DFIPs and CFPs
        
Components to be included (non-exhaustive list):

1. Stage of voting cycle i.e. Proposal Submission, Request for Comment, Voting.
    1. Time left for current stage, time left for current cycle
2. Global stats
    1. Total number of proposals submitted
        1. Upon hover, we can show number of DFIPs and CFPs
    2. Total votes registered
    3. Number of proposals voted yes
3. List of proposals, highlight key information such as:
    1. Title of proposal
    2. Name of Requester(s)
    3. Type of proposal (CFP or DFIP)
    4. Voting process/outcome
4. Current and past proposals tab
    1. Current proposals (This tab should only be available during an active CFP cycle)
        - Users should be able to click into respective proposals to view more
        - Users should be able to view the voting process
            - 3 states
                - Before voting stage begins → No interim vote results
                - During voting stage → Display interim vote results
                - After voting stage (while reward distribution is ongoing) → Show finalised voting results and status
                    - E.g. 90% Yes | 10% No, `Completed`
                    - E.g. 40% Yes | 60% No, `Rejected`
    2. Past proposals
        - Users should be able to click into respective proposals to view more
        - Finalised results and status associated with each proposal should be displayed
            - E.g. 90% Yes | 10% No, `Completed`
            - E.g. 40% Yes | 60% No, `Rejected`

**Individual proposal page (CFP)**

This page should:

1. Showcase the details of individual proposals
2. Allow users to be able to view discussions taking place on Reddit, Github etc.
3. Allow users to take part in the discussion on the respective platforms (allowing them to link out)

Components to be included (non-exhaustive list):

1. Proposal Overview
    1. Title of proposal
    2. Requester(s)
    3. Receiving address
    4. Proposal Unique ID (?)
    5. Amount requested in DFI (per cycle)
    6. Number of payment cycles requested
    7. Date submitted (last edited)
    8. Voting process/ outcome
    9. Proposal fee (10 DFI) txid (?)
2. Proposal details
    1. Elaboration of proposal (submitted by proposer)
    2. Preview of discussion thread(s)
    3. Links to discussion thread(s)
        1. Reddit, Github, Twitter, Youtube, Discord
    

**Individual proposal page (DFIP)**

This page should:

1. Showcase the details of individual proposals
2. Allow users to be able to view discussions taking place on Reddit, Github etc.
3. Allow users to take part in the discussion on the respective platforms (allowing them to link out)

Components to be included (non-exhaustive list):

1. Proposal Overview
    1. Title of proposal
    2. Requester(s)
    3. Proposal Unique ID (?)
    4. Date submitted (last edited)
    5. Voting process/ outcome
    6. Proposal fee (50 DFI) txid (?)
2. Proposal details
    1. Elaboration of proposal (submitted by proposer)
    2. Preview of discussion thread(s)
    3. Links to discussion thread(s)
        1. Reddit, Github, Twitter, Youtube, Discord

## Tasks

- [ ]  Proposals overview page ("Governance")
- [ ]  Individual proposal page (CFP)
- [ ]  Individual proposal page (DFIP)

## Other remarks

- Not allowing users to vote in this MVP

## Question

- Do we still need to include proposal fee txid given that the proposal submission happens on chain?
- Will there be a unique ID for each proposal?
- Do we need to display proposals for Allocation of Block Rewards?

## Sign-off by
- @fuxingloh 
- @jtlntno-cake
